### ISSUE TITLE
simple_with_value.json test

### ISSUE THREAD

**Issue by JStudent97** [alexandruradovici/alf2018#19]
Although in this test the input is : 
"{Variable definition with value}
define variable : int := 0"
the json it's the same with the previous test which was without value, just variable definition.
The previous test is called simple.alf.json with the input:
"{Variable definition}
define variable : int" => as i said , with no value. The .json to these 2 tests is the same(I mean the same format,without any new nodes in the AST);is this ok?

**Comment by ClaudiaDumitru** [comment]
The tests have been modified. All variable definitions with values now have a value property (the node for the specified value). If there is no value, this property will be missing.

**Comment by buzicaandrei12** [comment]
Lol yes. Yesterday the tests on github had values. What happened ?

**Comment by alexandruradovici** [comment]
Fixed
