### ISSUE TITLE
[design language]Tests for errors

### ISSUE THREAD

**Issue by LaurentiuTanase** [alexandruradovici/alf2018#3]
I don't find any sense in drawing something or modifying something if the line has errors. It's a complete non-sense. I understand that if there is an error to be ignored and continue to parse the file, but to execute something that has errors it's beyond my capabilities of understanding.

**Comment by alexandruradovici** [comment]
Lines with errors are ignored when drawing. If you find a line that has an error, you print the error and skip it.

**Comment by LaurentiuTanase** [comment]
Okay, thanks.
