### ISSUE TITLE
VMChecker ERROR

### ISSUE THREAD

**Issue by LaurentiuTanase** [alexandruradovici/alf2018#4]
![github](https://user-images.githubusercontent.com/36710850/37595663-45de45d6-2b82-11e8-8993-4f0f641eafab.png)

I have the following issue with VMChecker. It doesn't run all the tests...

**Comment by alexandruradovici** [comment]
The bug is fixed, the checker times out now, this is why it does not run all the tests. I will enlarge the timeout.

**Comment by LaurentiuTanase** [comment]
Thank you
