### ISSUE TITLE
Possibly wrong test operations.dsn

### ISSUE THREAD

**Issue by JStudent97** [alexandruradovici/alf2018#7]
operations.dsn has 2 lines with errors in it:
 ELLIPSE: position 100  (line 12)
CIRCLE:   30  50  %radius (line 13)
in your test, the code displays only 2 errors : 
"ERROR LINE 12: ELLIPSE has 4 parameters, you wrote 2
ERROR LINE 13: CIRCLE parameter 3 requires a number or a variable, you wrote %radius"
BUT there should be 3 errors : 
"ERROR LINE 12: ELLIPSE has 4 parameters, you wrote 2
ERROR LINE 12: ELLIPSE parameter 1 requires a number or a variable, you wrote position
ERROR LINE 13: CIRCLE parameter 3 requires a number or a variable, you wrote %radius"
am I wrong?
my code displays all 3 errors and because of that the test fails on vmChecker

**Comment by alexandruradovici** [comment]
There should be only one error per line, in the order specified in the homework. When you find an error, you write it and ignore that line.

**Comment by JStudent97** [comment]
fixed it. Thank you

**Comment by JStudent97** [comment]
Just found another similar error in while_error_parameters; your test displays only 3 errors:
"ERROR LINE 4: WHILE has 1 parameters, you wrote 3
ERROR LINE 6: COLOR parameter 1 requires one of (pen, fill), you wrote blue
ERROR LINE 10: REPEAT and no LOOP or WHILE"

in the code there is still another error on line 14 : 
"COLOR: pen 0 0 300"

my code displays all the 4 errors : 
"ERROR LINE 4: WHILE has 1 parameters, you wrote 3
ERROR LINE 6: COLOR parameter 1 requires one of (pen, fill), you wrote blue
ERROR LINE 10: REPEAT and no LOOP or WHILE
ERROR LINE 14: COLOR parameter 4 requires a number or a variable between [0,255], you wrote 300 "

the .svg file is exactly the same.

**Comment by JStudent97** [comment]
[test2.zip](https://github.com/alexandruradovici/alf2018/files/1826336/test2.zip)
Still , the error on vmChecker signals a pixel difference , not the outputs, but the .svg file is the  same with the one in your test. Why the error?

**Comment by JStudent97** [comment]
the Error has been fixed. Thank you
